### ISSUE TITLE
Submission Gists

### ISSUE THREAD

**Issue by mcordell** [everydev1618/rtanques#1]
Put your submission gists here

**Comment by thmzlt** [comment]
[Team Four](https://gist.github.com/thmzlt/33758f97277601942b4d)

**Comment by cmolenda** [comment]
Team 1: https://gist.github.com/cmolenda/6d1c9a9566468af42b52

**Comment by chrisdambrosio** [comment]
Team 4: https://gist.github.com/thmzlt/33758f97277601942b4d

**Comment by testflyjets** [comment]
Team 3: https://gist.github.com/testflyjets/35af60a5988d1460ccab
